import { DatabaseSync } from 'node:sqlite';
import { createHash, randomBytes } from 'node:crypto';
import { questions, type Question } from './questions.js';
import type { RoomView, Phase } from '../shared/types.js';

const codeChars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const token=()=>randomBytes(24).toString('base64url');
const id=()=>randomBytes(10).toString('hex');
const normalize=(s:string)=>s.trim().replace(/\s+/g,' ').slice(0,20);
const makeCode=()=>Array.from({length:5},()=>codeChars[Math.floor(Math.random()*codeChars.length)]).join('');

export class GameStore {
  db: DatabaseSync; timers=new Map<string,NodeJS.Timeout>(); durationMs:number; onChange?: (code:string)=>void;
  constructor(path='data/trivia.db', durationMs=30_000) {
    this.db=new DatabaseSync(path); this.durationMs=durationMs; this.db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;');
    this.db.exec(`CREATE TABLE IF NOT EXISTS rooms(code TEXT PRIMARY KEY, phase TEXT NOT NULL, round INTEGER NOT NULL DEFAULT 0, deck TEXT NOT NULL DEFAULT '[]', previous TEXT NOT NULL DEFAULT '[]', deadline INTEGER, created INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS players(id TEXT PRIMARY KEY, room_code TEXT NOT NULL REFERENCES rooms(code), nickname TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, score INTEGER NOT NULL DEFAULT 0, is_host INTEGER NOT NULL DEFAULT 0, connected INTEGER NOT NULL DEFAULT 0, joined INTEGER NOT NULL, UNIQUE(room_code,nickname COLLATE NOCASE));
      CREATE TABLE IF NOT EXISTS answers(room_code TEXT NOT NULL, round INTEGER NOT NULL, player_id TEXT NOT NULL REFERENCES players(id), choice INTEGER, correct INTEGER NOT NULL DEFAULT 0, submitted INTEGER NOT NULL, PRIMARY KEY(room_code,round,player_id));`);
    this.recover();
  }
  hash(t:string){return createHash('sha256').update(t).digest('base64url')}
  recover(){ for(const r of this.db.prepare("SELECT code,deadline FROM rooms WHERE phase='question'").all() as any[]) this.arm(r.code,r.deadline); }
  create(nickname:string){ const n=normalize(nickname); if(!n) throw Error('Enter a nickname.'); let code=makeCode(); while(this.db.prepare('SELECT 1 FROM rooms WHERE code=?').get(code)) code=makeCode(); const t=token(),pid=id(); this.db.exec('BEGIN IMMEDIATE'); try{this.db.prepare('INSERT INTO rooms(code,phase,created) VALUES(?,?,?)').run(code,'lobby',Date.now());this.db.prepare('INSERT INTO players(id,room_code,nickname,token_hash,is_host,connected,joined) VALUES(?,?,?,?,1,1,?)').run(pid,code,n,this.hash(t),Date.now());this.db.exec('COMMIT')}catch(e){this.db.exec('ROLLBACK');throw e} return {code,token:t}; }
  join(code:string,nickname:string){ const c=code.trim().toUpperCase(),n=normalize(nickname); if(!n) throw Error('Enter a nickname.'); const t=token(),pid=id(); this.db.exec('BEGIN IMMEDIATE'); try{const room=this.db.prepare('SELECT phase FROM rooms WHERE code=?').get(c) as any;if(!room)throw Error('Room not found.');if(room.phase!=='lobby')throw Error('This match has already started.');const count=(this.db.prepare('SELECT COUNT(*) n FROM players WHERE room_code=?').get(c) as any).n;if(count>=8)throw Error('This room is full.');this.db.prepare('INSERT INTO players(id,room_code,nickname,token_hash,connected,joined) VALUES(?,?,?,?,1,?)').run(pid,c,n,this.hash(t),Date.now());this.db.exec('COMMIT')}catch(e:any){this.db.exec('ROLLBACK');if(String(e.message).includes('UNIQUE'))throw Error('That nickname is already in use.');throw e}return{code:c,token:t}; }
  auth(t:string){if(!t)throw Error('Session expired. Rejoin the room.');const p=this.db.prepare('SELECT * FROM players WHERE token_hash=?').get(this.hash(t)) as any;if(!p)throw Error('Session expired. Rejoin the room.');return p}
  connect(t:string,on:boolean){const p=this.auth(t);this.db.prepare('UPDATE players SET connected=? WHERE id=?').run(on?1:0,p.id);return p.room_code}
  requireHost(t:string){const p=this.auth(t);if(!p.is_host)throw Error('Only the host can do that.');return p}
  pick(previous:number[]){const pool=questions.filter(q=>!previous.includes(q.id));const source=pool.length>=10?pool:[...questions];for(let i=source.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[source[i],source[j]]=[source[j],source[i]]}return source.slice(0,10).map(q=>q.id)}
  start(t:string){const p=this.requireHost(t);const r=this.room(p.room_code);if(r.phase!=='lobby')throw Error('The match is not in the lobby.');const count=(this.db.prepare('SELECT COUNT(*) n FROM players WHERE room_code=?').get(p.room_code) as any).n;if(count<2)throw Error('At least 2 players are required.');const deck=this.pick(JSON.parse(r.previous));this.db.exec('BEGIN IMMEDIATE');try{this.db.prepare('UPDATE players SET score=0 WHERE room_code=?').run(p.room_code);this.db.prepare('DELETE FROM answers WHERE room_code=?').run(p.room_code);this.db.prepare("UPDATE rooms SET phase='question',round=1,deck=?,deadline=? WHERE code=?").run(JSON.stringify(deck),Date.now()+this.durationMs,p.room_code);this.db.exec('COMMIT')}catch(e){this.db.exec('ROLLBACK');throw e}this.arm(p.room_code);}
  submit(t:string,round:number,choice:number){const p=this.auth(t);if(!Number.isInteger(choice)||choice<0||choice>3)throw Error('Invalid answer.');this.db.exec('BEGIN IMMEDIATE');try{const r=this.room(p.room_code);if(r.phase!=='question'||r.round!==round)throw Error('That round is no longer accepting answers.');if(!r.deadline||Date.now()>=r.deadline)throw Error('Time is up.');const q=this.question(r);this.db.prepare('INSERT INTO answers(room_code,round,player_id,choice,correct,submitted) VALUES(?,?,?,?,?,?)').run(r.code,round,p.id,choice,choice===q.correct?1:0,Date.now());const counts=this.db.prepare('SELECT (SELECT COUNT(*) FROM players WHERE room_code=?) total,(SELECT COUNT(*) FROM answers WHERE room_code=? AND round=?) answered').get(r.code,r.code,round) as any;if(counts.answered===counts.total)this.revealLocked(r.code,round);this.db.exec('COMMIT')}catch(e:any){this.db.exec('ROLLBACK');if(String(e.message).includes('UNIQUE'))throw Error('Your answer is already locked.');throw e}}
  advance(t:string){const p=this.requireHost(t);this.db.exec('BEGIN IMMEDIATE');try{const r=this.room(p.room_code);if(r.phase!=='reveal')throw Error('Wait for the answer reveal.');if(r.round>=10){this.db.prepare("UPDATE rooms SET phase='finished',deadline=NULL WHERE code=?").run(r.code)}else{this.db.prepare("UPDATE rooms SET phase='question',round=round+1,deadline=? WHERE code=?").run(Date.now()+this.durationMs,r.code)}this.db.exec('COMMIT')}catch(e){this.db.exec('ROLLBACK');throw e}const r=this.room(p.room_code);if(r.phase==='question')this.arm(r.code);}
  lobby(t:string){const p=this.requireHost(t);const r=this.room(p.room_code);if(r.phase!=='finished')throw Error('Finish the match before returning to the lobby.');this.db.prepare("UPDATE rooms SET phase='lobby',round=0,previous=deck,deck='[]',deadline=NULL WHERE code=?").run(r.code)}
  timeout(code:string,round:number){this.db.exec('BEGIN IMMEDIATE');try{const r=this.room(code);if(r.phase==='question'&&r.round===round&&r.deadline&&Date.now()>=r.deadline)this.revealLocked(code,round);this.db.exec('COMMIT');this.onChange?.(code)}catch(e){this.db.exec('ROLLBACK');throw e}}
  revealLocked(code:string,round:number){this.db.prepare('UPDATE players SET score=score+100 WHERE id IN (SELECT player_id FROM answers WHERE room_code=? AND round=? AND correct=1)').run(code,round);this.db.prepare("UPDATE rooms SET phase='reveal',deadline=NULL WHERE code=? AND phase='question' AND round=?").run(code,round);const timer=this.timers.get(code);if(timer)clearTimeout(timer);this.timers.delete(code)}
  arm(code:string,deadline?:number){const r=this.room(code);const d=deadline??r.deadline;if(!d)return;const old=this.timers.get(code);if(old)clearTimeout(old);this.timers.set(code,setTimeout(()=>this.timeout(code,r.round),Math.max(0,d-Date.now()+5)))}
  room(code:string){const r=this.db.prepare('SELECT * FROM rooms WHERE code=?').get(code) as any;if(!r)throw Error('Room not found.');return r}
  question(r:any):Question{const q=questions.find(x=>x.id===JSON.parse(r.deck)[r.round-1]);if(!q)throw Error('Question unavailable.');return q}
  view(t:string):RoomView{const self=this.auth(t),r=this.room(self.room_code),ps=this.db.prepare('SELECT id,nickname,score,connected,is_host FROM players WHERE room_code=? ORDER BY score DESC,joined').all(r.code) as any[];const q=r.round?this.question(r):null;const ans=this.db.prepare('SELECT player_id,choice FROM answers WHERE room_code=? AND round=?').all(r.code,r.round) as any[];const amap=Object.fromEntries(ans.map(a=>[a.player_id,a.choice]));const top=ps.length?ps[0].score:0;return{code:r.code,phase:r.phase as Phase,round:r.round,totalRounds:10,deadline:r.deadline,question:q?{id:q.id,topic:q.topic,prompt:q.prompt,options:q.options}:null,reveal:r.phase==='reveal'||r.phase==='finished'?{correctIndex:q?.correct??-1,answers:Object.fromEntries(ps.map(p=>[p.id,amap[p.id]??null]))}:null,players:ps.map(p=>({...p,isHost:!!p.is_host,connected:!!p.connected,hasAnswered:Object.hasOwn(amap,p.id)})),winners:r.phase==='finished'?ps.filter(p=>p.score===top).map(p=>p.nickname):[],isHost:!!self.is_host,selfId:self.id}}
  close(){for(const t of this.timers.values())clearTimeout(t);this.db.close()}
}
