import type { Topic } from '../shared/types.js';
export interface Question { id: number; topic: Topic; prompt: string; options: [string,string,string,string]; correct: number }
const rows: Array<[Topic,string,[string,string,string,string],number]> = [
['Video Games','Which company created the Mario franchise?',['Sega','Nintendo','Sony','Atari'],1],
['Video Games','What is the name of Link’s kingdom in The Legend of Zelda?',['Hyrule','Midgar','Rapture','Albion'],0],
['Video Games','In Minecraft, which material is required to build a Nether portal?',['Quartz','Obsidian','Bedrock','Emerald'],1],
['Video Games','Which game features the city of Rapture?',['BioShock','Fallout 3','Portal 2','Dishonored'],0],
['Video Games','What color is Pac-Man?',['Blue','Red','Yellow','Green'],2],
['Video Games','Which series includes the character Master Chief?',['Halo','Doom','Metroid','Destiny'],0],
['Video Games','What are Tetris pieces commonly called?',['Blocks','Tetrominoes','Pixels','Bricks'],1],
['Video Games','Which game popularized the battle bus?',['Apex Legends','PUBG','Fortnite','Overwatch'],2],
['Video Games','Who is Sonic the Hedgehog’s main enemy?',['Dr. Wily','Bowser','Dr. Eggman','Ganondorf'],2],
['Video Games','Which studio developed The Last of Us?',['Naughty Dog','Valve','Bungie','Rare'],0],
['Movies','Who directed Jaws?',['George Lucas','Steven Spielberg','James Cameron','Ridley Scott'],1],
['Movies','What color pill does Neo take in The Matrix?',['Blue','Red','Green','White'],1],
['Movies','Which film features a DeLorean time machine?',['Looper','Back to the Future','Interstellar','Tenet'],1],
['Movies','What is the fictional metal in Black Panther?',['Adamantium','Unobtainium','Vibranium','Beskar'],2],
['Movies','Who played Jack in Titanic?',['Brad Pitt','Matt Damon','Leonardo DiCaprio','Tom Cruise'],2],
['Movies','Which movie includes the line about needing a bigger boat?',['Jaws','Titanic','Finding Nemo','The Abyss'],0],
['Movies','What kind of fish is Nemo?',['Clownfish','Angelfish','Goldfish','Blue tang'],0],
['Movies','Which trilogy centers on the One Ring?',['The Hobbit','The Lord of the Rings','Star Wars','The Matrix'],1],
['Movies','Who directed Get Out?',['Jordan Peele','Spike Lee','Barry Jenkins','Ava DuVernay'],0],
['Movies','In Toy Story, what type of toy is Buzz?',['Robot','Astronaut action figure','Race car','Dinosaur'],1],
['Music','How many strings does a standard guitar have?',['Four','Five','Six','Eight'],2],
['Music','Which artist released the album Thriller?',['Prince','Michael Jackson','Stevie Wonder','David Bowie'],1],
['Music','Which band recorded Bohemian Rhapsody?',['Queen','The Beatles','ABBA','U2'],0],
['Music','What is the highest female classical singing voice?',['Alto','Tenor','Soprano','Baritone'],2],
['Music','Which instrument has 88 keys in its standard form?',['Accordion','Organ','Piano','Harpsichord'],2],
['Music','Which singer is known as the Queen of Soul?',['Aretha Franklin','Diana Ross','Tina Turner','Whitney Houston'],0],
['Music','Which city is associated with the Motown sound?',['Chicago','Detroit','Memphis','Nashville'],1],
['Music','What does BPM measure in music?',['Pitch','Tempo','Volume','Harmony'],1],
['Music','Which composer wrote the Fifth Symphony’s famous opening motif?',['Mozart','Bach','Beethoven','Chopin'],2],
['Music','Which genre originated in Jamaica in the late 1960s?',['Reggae','Disco','Grunge','Techno'],0],
['TV','Which sitcom follows six friends living in New York City?',['Cheers','Friends','Frasier','Seinfeld'],1],
['TV','What is the name of the coffee shop in Friends?',['Central Perk','Monk’s Café','Luke’s Diner','Café Nervosa'],0],
['TV','Which series features the Upside Down?',['Lost','Dark','Stranger Things','The X-Files'],2],
['TV','Who lives in a pineapple under the sea?',['Patrick Star','SpongeBob SquarePants','Squidward','Mr. Krabs'],1],
['TV','Which family lives at 742 Evergreen Terrace?',['The Griffins','The Belchers','The Simpsons','The Smiths'],2],
['TV','What is the paper company in The Office (US)?',['Wernham Hogg','Dunder Mifflin','Sabre Paper','Sterling Cooper'],1],
['TV','Which fantasy series features the Iron Throne?',['The Witcher','Game of Thrones','Merlin','Vikings'],1],
['TV','What is Eleven’s favorite snack in Stranger Things?',['Pop-Tarts','Twinkies','Eggo waffles','Oreos'],2],
['TV','Which show follows chemistry teacher Walter White?',['Ozark','Better Call Saul','Breaking Bad','Narcos'],2],
['TV','Which animated show is set in the town of Quahog?',['Family Guy','South Park','Futurama','Bob’s Burgers'],0]
];
export const questions: Question[] = rows.map((q,i)=>({id:i+1,topic:q[0],prompt:q[1],options:q[2],correct:q[3]}));
