import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{io}from'socket.io-client';import type{Ack,RoomView}from'../shared/types';import'./style.css';
const socket=io(import.meta.env.DEV?'http://localhost:3001':undefined,{autoConnect:true});
function App(){const[state,setState]=useState<RoomView|null>(null),[token,setToken]=useState(''),[nickname,setNickname]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[connected,setConnected]=useState(socket.connected),[now,setNow]=useState(Date.now());
useEffect(()=>{const saved=new URLSearchParams(location.hash.slice(1)).get('session')||'';if(saved)setToken(saved);socket.on('connect',()=>{setConnected(true);const current=new URLSearchParams(location.hash.slice(1)).get('session')||'';if(current)socket.emit('resume',{token:current},(a:Ack<RoomView>)=>a.ok?setState(a.data!):setError(a.error!))});socket.on('disconnect',()=>setConnected(false));socket.on('state',setState);return()=>{socket.off('state',setState);socket.off('connect');socket.off('disconnect')}},[]);
useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(t)},[]);useEffect(()=>{if(token&&connected&&!state)socket.emit('resume',{token},(a:Ack<RoomView>)=>a.ok?setState(a.data!):setError(a.error!))},[token,connected,state]);
const call=(event:string,payload:object={})=>{setBusy(true);setError('');socket.emit(event,payload,(a:Ack<any>)=>{setBusy(false);if(!a.ok)return setError(a.error||'Request failed.');if(a.data?.token){setToken(a.data.token);setState(a.data.state);location.hash=new URLSearchParams({session:a.data.token}).toString()}})};
const me=state?.players.find(p=>p.id===state.selfId),secs=Math.max(0,Math.ceil(((state?.deadline||0)-now)/1000));const ordered=useMemo(()=>state?[...state.players].sort((a,b)=>b.score-a.score):[],[state]);
if(!state)return <main><Header connected={connected}/><section className="hero"><p className="eyebrow">REAL-TIME PARTY TRIVIA</p><h1>Ready to<br/><span>throw down?</span></h1><p className="lede">Ten questions. Four pop-culture worlds. One leaderboard.</p><div className="entry"><label>Nickname<input maxLength={20} value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="Your nickname" autoComplete="nickname"/></label><button disabled={busy||!connected} onClick={()=>call('create',{nickname})}>Create a room</button><div className="or">or join a showdown</div><label>Room code<input className="code" maxLength={5} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="ABCDE"/></label><button className="secondary" disabled={busy||!connected} onClick={()=>call('join',{nickname,code})}>Join room</button>{error&&<p role="alert" className="error">{error}</p>}</div></section><Rules/></main>;
return <main><Header connected={connected}/><section className="game"><div className="top"><div><p className="eyebrow">ROOM CODE</p><button className="roomcode" onClick={()=>navigator.clipboard?.writeText(state.code)} aria-label="Copy room code">{state.code}</button></div>{state.phase!=='lobby'&&<div className="round">QUESTION <b>{state.round}</b> / 10</div>}</div>{error&&<p role="alert" className="error">{error}</p>}
{state.phase==='lobby'&&<Lobby state={state} busy={busy} act={call}/>} {state.phase==='question'&&state.question&&<Question state={state} me={me} secs={secs} busy={busy} act={call}/>} {state.phase==='reveal'&&state.question&&<Reveal state={state} busy={busy} act={call}/>} {state.phase==='finished'&&<Finished state={state} busy={busy} act={call}/>}<Leaderboard players={ordered} self={state.selfId}/></section></main>}
const Header=({connected}:{connected:boolean})=><header><div className="brand"><i>TS</i><span>TRIVIA<br/>SHOWDOWN</span></div><span className={'status '+(connected?'online':'offline')}><b/> {connected?'CONNECTED':'RECONNECTING'}</span></header>;
const Rules=()=> <section className="rules"><p className="eyebrow">HOW TO PLAY</p><h2>Fast facts. No speed bonus.</h2><div className="rulegrid"><article><b>01</b><h3>Gather</h3><p>2–8 players join with the room code. The host plays too.</p></article><article><b>02</b><h3>Lock it in</h3><p>Choose once within 30 seconds. Your first answer is final.</p></article><article><b>03</b><h3>Score</h3><p>Correct answers earn 100 points. Highest total after ten wins.</p></article></div></section>;
function Lobby({state,busy,act}:{state:RoomView,busy:boolean,act:any}){return <section className="panel lobby"><p className="eyebrow">THE GREEN ROOM</p><h2>Players are joining</h2><p>Share the code above. The showdown supports 2–8 players.</p><div className="chips">{state.players.map(p=><span key={p.id}>{p.nickname}{p.isHost?' ★':''}</span>)}</div>{state.isHost?<button disabled={busy||state.players.length<2} onClick={()=>act('start')}>Start showdown <span>→</span></button>:<div className="waiting"><i/> Waiting for the host to start…</div>}</section>}
function Question({state,me,secs,busy,act}:{state:RoomView,me:any,secs:number,busy:boolean,act:any}){return <section className="panel question"><div className="qmeta"><span>{state.question!.topic}</span><strong className={secs<=5?'urgent':''}>{secs}s</strong></div><h2>{state.question!.prompt}</h2><div className="answers">{state.question!.options.map((o,i)=><button key={o} disabled={busy||me?.hasAnswered||secs===0} onClick={()=>act('answer',{round:state.round,choice:i})}><b>{String.fromCharCode(65+i)}</b>{o}</button>)}</div>{me?.hasAnswered&&<p className="locked">✓ Answer locked. Waiting for everyone…</p>}</section>}
function Reveal({state,busy,act}:{state:RoomView,busy:boolean,act:any}){return <section className="panel reveal"><p className="eyebrow">ANSWER REVEAL</p><h2>{state.question!.prompt}</h2><div className="answers">{state.question!.options.map((o,i)=><div className={i===state.reveal!.correctIndex?'correct':'dim'} key={o}><b>{String.fromCharCode(65+i)}</b>{o}{i===state.reveal!.correctIndex&&<span>✓</span>}</div>)}</div>{state.isHost?<button disabled={busy} onClick={()=>act('advance')}>{state.round===10?'See final results':'Next question'} <span>→</span></button>:<p className="waiting"><i/> Host is reviewing the answer…</p>}</section>}
function Finished({state,busy,act}:{state:RoomView,busy:boolean,act:any}){return <section className="panel finish"><p className="eyebrow">FINAL RESULTS</p><div className="trophy">♛</div><h2>{state.winners.length>1?'Shared victory!':'Showdown champion!'}</h2><p className="winner">{state.winners.join(' & ')}</p>{state.isHost?<button disabled={busy} onClick={()=>act('lobby')}>Return to lobby & replay</button>:<p>Waiting for the host to set up a rematch.</p>}</section>}
function Leaderboard({players,self}:{players:RoomView['players'],self:string}){return <aside className="leader"><div><p className="eyebrow">LEADERBOARD</p><span>{players.length}/8 PLAYERS</span></div>{players.map((p,i)=><div className={'player '+(p.id===self?'you':'')} key={p.id}><b>{i+1}</b><span>{p.nickname}{p.isHost?' ★':''}<small>{p.connected?'ONLINE':'DISCONNECTED'}</small></span><strong>{p.score}</strong></div>)}</aside>}
createRoot(document.getElementById('root')!).render(<App/>);
